#!/bin/bash
mkdir -p /home/node/.local/share/opencode/
cat << EOF > /home/node/.local/share/opencode/auth.json
{
	"deepinfra": {
		"type": "api",
		"key": "${DEEPINFRA_TOKEN}"
	}
}
EOF
/usr/local/bin/opencode
